apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::621352866489:role/k8sgpt-dev-eks-node-role
      groups:                                                                                                                                                                                                                                                                                                                                 
        - system:bootstrappers                                                                                                                                                                                      
        - system:nodes                                                                                                                                                                                              
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::621352866489:role/EKSRORole   
      groups:                                                                                                                                                                                                     
        - rundeck-readonly
      username: rundeck                                                                                                                                             
                                 