apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rundeck-ro
rules:
# Allow for all core API resources except secrets
- apiGroups: [""]  # Core API group
  resources:
  - pods
  - services
  - configmaps
  - nodes
  - namespaces
  - persistentvolumes
  - persistentvolumeclaims
  - endpoints
  - events
  - replicationcontrollers
  - resourcequotas
  - serviceaccounts
  - limitranges
  - podtemplates
  - componentstatuses
  - bindings
  verbs: ["get", "list", "watch"]

# Allow for common extended API resources
- apiGroups: ["apps"]
  resources:
  - deployments
  - replicasets
  - statefulsets
  - daemonsets
  - controllerrevisions
  verbs: ["get", "list", "watch"]

- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["get", "list", "watch"]

- apiGroups: ["extensions"]
  resources:
  - deployments
  - replicasets
  - daemonsets
  - networkpolicies
  verbs: ["get", "list", "watch"]

- apiGroups: ["networking.k8s.io"]
  resources:
  - networkpolicies
  - ingresses
  - ingressclasses
  verbs: ["get", "list", "watch"]

- apiGroups: ["storage.k8s.io"]
  resources:
  - storageclasses
  - volumeattachments
  - csidrivers
  - csinodes
  verbs: ["get", "list", "watch"]

- apiGroups: ["policy"]
  resources:
  - poddisruptionbudgets
  verbs: ["get", "list", "watch"]

- apiGroups: ["autoscaling"]
  resources:
  - horizontalpodautoscalers
  verbs: ["get", "list", "watch"]

# Note: No rule for secrets - they are explicitly excluded
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rundeck-ro-binding
subjects:
  - kind: Group
    name: rundeck-readonly
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: rundeck-ro
  apiGroup: rbac.authorization.k8s.io